version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "3001:80"
    depends_on:
      - service1
      - service2

  service1:
    build: ./service1
    ports:
      - "8001:8000"
    volumes:
      - ./service1:/app

  service2:
    build: ./service2
    ports:
      - "8002:8000"
    volumes:
      - ./service2:/app
