apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: swe590-project-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.allow-http: "true"
    # Health check annotations
    ingress.gcp.kubernetes.io/v1beta1.BackendConfig: '{
      "healthCheck": {
        "checkIntervalSec": 30,
        "timeoutSec": 5,
        "healthyThreshold": 1,
        "unhealthyThreshold": 2,
        "type": "HTTP",
        "requestPath": "/",
        "port": 8000
      }
    }'
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
      - path: /service1
        pathType: Prefix
        backend:
          service:
            name: service1
            port:
              number: 8000
      - path: /service2
        pathType: Prefix
        backend:
          service:
            name: service2
            port:
              number: 8000
